# SealedSecret fuer Datenbank-Anmeldedaten
# Diese Datei kann sicher in Git gespeichert werden
#
# WICHTIG: Die verschluesselten Werte unten sind BEISPIELE/PLATZHALTER!
# Sie muessen mit kubeseal und dem echten Public Key des Controllers neu erstellt werden.
#
# Generierung:
# kubeseal --controller-name=sealed-secrets-controller \
#          --controller-namespace=sealed-secrets \
#          --format yaml \
#          < db-credentials-secret.template.yaml \
#          > db-credentials-sealed.yaml

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: development
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
spec:
  encryptedData:
    # PLATZHALTER - Diese Werte muessen mit kubeseal neu generiert werden!
    # Die echten verschluesselten Werte werden vom Controller entschluesselt
    username: AgBY8...ENCRYPTED_VALUE_PLACEHOLDER...==
    password: AgCK9...ENCRYPTED_VALUE_PLACEHOLDER...==
  template:
    metadata:
      name: db-credentials
      namespace: development
    type: Opaque
